name: Bramble RP2040 Emulator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set build output dir
        id: strings
        shell: bash
        run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-dir }} --config ${{ matrix.build_type }} -j$(nproc)

      - name: Run tests
        working-directory: ${{ steps.strings.outputs.build-dir }}
        run: ./bramble_tests

      - name: Upload bramble binary
        uses: actions/upload-artifact@v4
        with:
          name: bramble-${{ matrix.c_compiler }}-${{ matrix.build_type }}
          path: ${{ steps.strings.outputs.build-dir }}/bramble
